### ISSUE TITLE
Selecting non-.cfm file doesn't update UI correctly

### ISSUE THREAD

**Issue by bdw429s** [dapywell/cfperformanceexplorer#2]
If I view a .cfm file and then next I click a .txt file, the message `The requested file [ views\main\data.txt ] is not a readable text document.` is returned from the Ajax call, but the UI doesn't not correctly show this message.

Instead, the `File:` portion of the page is updated to show the new file name but the line metrics on the screen are that of the last .cfm file viewed.

**Comment by Cumminsc9** [comment]
When the files are added to the file browser it checks to see if the file type is equal to either .cfm or .cfc and if not they are not they are not added. This should stop users from selecting non CFML files.

**Comment by bdw429s** [comment]
What if they are using `.cfml`?  Honestly, why limit them at all?  Someone was just asking yesterday in Slack how to process `.do` files as CFML.  Why not just accept what they click and show metrics if they exist?  The only downside I can see, is if they click a binary file, which brings up another good question-- how does this tool behave for compiled CFML templates?

**Comment by Cumminsc9** [comment]
I have another fix awaiting for commit after testing that displays a message if the file has not yet been profiled. I can extend this notification to cover other files that can't be displayed. Otherwise, I can look at not displaying the file if no profile data exists for the file. 

There are many option that can be tried here to solve the issue. I'll reopen the issue for now, and take a look come Monday.

**Comment by Cumminsc9** [comment]
I have now removed the file limiter, allowing users to select all file types. However, those that contain no metrics will display the contents of the file including a warning message. The files that cannot be parsed now display nothing with a parse warning.
